CREATE TABLE CART (cart_id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10, INCREMENT BY 1));
CREATE TABLE ITEMS (id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 100, INCREMENT BY 1), cart_id INTEGER NOT NULL, FOREIGN KEY(cart_id) REFERENCES CART(cart_id));

CREATE TABLE CARTOIO (cart_id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 20, INCREMENT BY 1));
CREATE TABLE ITEMSOIO (id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 200, INCREMENT BY 1), cart_id INTEGER, FOREIGN KEY(cart_id) REFERENCES CARTOIO(cart_id));
